### ISSUE TITLE
node updated with PointSetNode.WithSubNodes() no longer has positions etc.

### ISSUE THREAD

**Issue by gnufu** [aardvark-platform/aardvark.algodat#14]
When I update the subnodes of a node with
```
let withUpdatedSubnodes = node.WithSubNodes(updatedSubnodes)
```
the node `withUpdatedSubnodes` does not hold the positions, colors, intensities etc. values of `node`

a workaround working for me is setting those properties afterwards again:
```
let oldProperties =
   node.Properties
   |> Seq.where (fun kvp -> kvp.Key <> Durable.Octree.NodeId && kvp.Key <> Durable.Octree.SubnodesGuids)
   |> ImmutableDictionary<Durable.Def, Object>.Empty.AddRange

 withUpdatedSubnodes.With(oldProperties).WriteToStore()
```

**Comment by stefanmaierhofer** [comment]
This is by design:
all node properties (except Cell, BoundingBoxExactGlobal, and PointCountTreeLeafs) are removed, because they would no longer be valid for new subnode data. Implicit recomputation of all these properties would be too expensive, e.g. when generating/merging large octrees, then many intermediate (structural) nodes are generated for which computing LoD data makes no sense and would introduce a very large overhead.

You can use LodExtensions.GenerateLod to explicitely recompute these properties.

**Comment by stefanmaierhofer** [comment]
additional info: all these properties that are removed depend on subnode data, e.g. are level-of-detail representations. When swapping out subnodes, the previous values no longer make sense.

**Comment by stefanmaierhofer** [comment]
PointSetNode.WithSubNodes() is mostly used for internal processing/construction of octrees and probably should **never** have been made public.
What is the use case you are trying to solve? @gnufu
